version: "3"
services:
  vitepress: #服务名
    build: # 使用Dockerfile构建镜像
      context: . # 指定 Dockerfile 所在目录
      dockerfile: Dockerfile # 指定 Dockerfile 文件名
    container_name: vitepress-blog # 容器名称
    ports:
      - 3000:80
