/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./.vitepress/components/BackToTop.vue')['default']
    EnglishWord: typeof import('./.vitepress/components/EnglishWord.vue')['default']
    EnglishWords: typeof import('./.vitepress/components/EnglishWords.vue')['default']
    ExampleSentence: typeof import('./.vitepress/components/ExampleSentence.vue')['default']
    Kbd: typeof import('./.vitepress/components/Kbd.vue')['default']
    NceComprehension: typeof import('./.vitepress/components/NceComprehension.vue')['default']
    NceTexts: typeof import('./.vitepress/components/NceTexts.vue')['default']
  }
}
